name: linting-and-test
on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-versions: '16'
      - run: npm install
      - run: npm run formating && npm run lint

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-versions: '16'
      - run: npm install
      - run: npm run test
